
@URL = https://tcv80m8o6d.execute-api.ap-southeast-1.amazonaws.com/


### Get all users
GET {{URL}}/users

### Create a user
POST {{URL}}/users
Content-Type: application/json

{
    "name": "coding2 addict",
    "email": "coding2@addict.com"
}

### Get a user
GET {{URL}}/users/1c8bcc8d-6282-4dec-bb46-40cf8d4605d7

### Update a user
PUT {{URL}}/users/1c8bcc8d-6282-4dec-bb46-40cf8d4605d7
Content-Type: application/json

{
    "name": "coding addict",
    "email": "coding@addict.com"
}

### Delete a user
DELETE {{URL}}/users/1c8bcc8d-6282-4dec-bb46-40cf8d4605d7
